# Practical 21

# Comparison between accuracy of Knn and Logistic regression and select which method is suitable for the given dataset

# ....................................................KNN....................................................

In [1]:
#importing the libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [2]:
df = pd.read_csv(r"D:\Machine Learning\User_Data.csv")  #importing the dataset

In [3]:
df.head()  #viewing the dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.describe()  #getting the baisc statistical values of the dataset

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [5]:
df["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [6]:
df.columns  #getting the column headings

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [7]:
#spliting the dataset into dependent and independent variables
x = df[['Age', 'EstimatedSalary']].values
print(x[0:5])
y = df[ 'Purchased'].values
print(y[0:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
[0 0 0 0 0]


In [8]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))  #scaling, fitting and transforming the independent variables
# in this step we are using anonymous objects. linking objects without makig them refer is called anonymous objects
x[0:10]

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283]])

In [9]:
from sklearn.model_selection import train_test_split  #spliting the training and testing dataset
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.neighbors import KNeighborsClassifier  # imprting the KNN classifier
from sklearn import metrics
k = 4
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)

In [11]:
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 4 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 4 is : 0.95


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [12]:
k = 5
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 5 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 5 is : 0.95


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [13]:
k = 8
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 8 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 8 is : 0.95


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [14]:
k = 8
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 8 is :", metrics.accuracy_score(ytest, predy))  
confusion_matrix = metrics.confusion_matrix(ytest, predy)  #creating the confusion matrix
print(confusion_matrix)

Accuracy of model at K = 8 is : 0.95
[[55  3]
 [ 1 21]]


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [15]:
print(metrics.classification_report(ytest, predy))
print("Accuracy of model at K = 8 is :", metrics.accuracy_score(ytest, predy))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

Accuracy of model at K = 8 is : 0.95


# ..............................................Logistic Regression..............................................

In [16]:
# Import the library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
data= pd.read_csv(r"D:\Machine Learning\User_Data.csv")  #import the dataset
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [18]:
# Input
x = data.iloc[:,[2,3]].values
#Output
y = data.iloc[:,4].values

In [19]:
from sklearn.model_selection import train_test_split  # Splitting the data in training and testing
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25 , random_state = 0 )

In [20]:
from sklearn.preprocessing import StandardScaler  # Scaling
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)
print(xtrain)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [21]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [22]:
y_pred = classifier.predict(xtest)

In [23]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
print("Confusion Matrix : \n" , cm)

Confusion Matrix : 
 [[65  3]
 [ 8 24]]


In [24]:
import sklearn.metrics as metrics  # Finding accuracy precision and recall
print ('Accuracy: ', metrics.accuracy_score(ytest,y_pred))
print ('Precision: ', metrics.precision_score(ytest,y_pred))
print ('Recall: ', metrics.recall_score(ytest,y_pred))

Accuracy:  0.89
Precision:  0.8888888888888888
Recall:  0.75


In [25]:
from sklearn.metrics import classification_report
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



# ......................................................Conclusion......................................................